import type { Category } from '../types';

export const DEFAULT_CATEGORIES: Category[] = [
  // Gastos
  {
    id: 'cat-exp-1',
    user_id: 'default',
    name: 'Alimentación',
    type: 'expense',
    icon_name: 'ForkKnife',
    color: '#F59E0B',
    is_system: true,
  },
  {
    id: 'cat-exp-2',
    user_id: 'default',
    name: 'Transporte',
    type: 'expense',
    icon_name: 'Car',
    color: '#3B82F6',
    is_system: true,
  },
  {
    id: 'cat-exp-3',
    user_id: 'default',
    name: 'Servicios del Hogar',
    type: 'expense',
    icon_name: 'House',
    color: '#8B5CF6',
    is_system: true,
  },
  {
    id: 'cat-exp-4',
    user_id: 'default',
    name: 'Entretenimiento',
    type: 'expense',
    icon_name: 'GameController',
    color: '#EC4899',
    is_system: true,
  },
  {
    id: 'cat-exp-5',
    user_id: 'default',
    name: 'Salud & Medicina',
    type: 'expense',
    icon_name: 'HeartStraight',
    color: '#EF4444',
    is_system: true,
  },
  {
    id: 'cat-exp-6',
    user_id: 'default',
    name: 'Compras Personales',
    type: 'expense',
    icon_name: 'Bag',
    color: '#14B8A6',
    is_system: true,
  },
  {
    id: 'cat-exp-7',
    user_id: 'default',
    name: 'Educación',
    type: 'expense',
    icon_name: 'GraduationCap',
    color: '#6366F1',
    is_system: true,
  },

  // Ingresos
  {
    id: 'cat-inc-1',
    user_id: 'default',
    name: 'Salario / Nómina',
    type: 'income',
    icon_name: 'Money',
    color: '#10B981',
    is_system: true,
  },
  {
    id: 'cat-inc-2',
    user_id: 'default',
    name: 'Freelance / Extras',
    type: 'income',
    icon_name: 'Briefcase',
    color: '#06B6D4',
    is_system: true,
  },
  {
    id: 'cat-inc-3',
    user_id: 'default',
    name: 'Rendimientos / Inversión',
    type: 'income',
    icon_name: 'TrendUp',
    color: '#84CC16',
    is_system: true,
  },
  {
    id: 'cat-inc-4',
    user_id: 'default',
    name: 'Ventas',
    type: 'income',
    icon_name: 'Tag',
    color: '#F97316',
    is_system: true,
  },
];
